### PR TITLE
added function for setting gpu fraction

### PR DESCRIPTION
**Pull request by johntyty912**
added function for setting gpu fraction

### CODE REVIEW

**Comment by abiller** [comment]
This does not work with the tf2.0 beta release, see https://www.tensorflow.org/beta/guide/using_gpu
...
  File "/home/worker/trains/tf2_yolo/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/worker/trains/tf2_yolo/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 48, in main
    tf.config.gpu.set_per_process_memory_fraction(FLAGS.gpu_fraction)
AttributeError: module 'tensorflow._api.v2.config' has no attribute 'gpu'

**Comment by zzh8829** [comment]
you are right im gonna revert this, this no longer works in beta
